src/WebApplication4/Models/product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BWSC.Models
{
    public class Product
    {
        public int ID { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        [DisplayFormat(DataFormatString = "{0:C}", ApplyFormatInEditMode = true)]
        public decimal SellingPrice { get; set; }
        public string ImageFileName { get; set; }
    }
}

src/WebApplication4/Controllers/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BWSC.Data;
using BWSC.Models;
using Microsoft.AspNetCore.Http;
using BWSC.Logic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace BWSC.Controllers
{
    public class CartItemsController : Controller
    {
        private readonly SwimmingClubContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private ISession _session => _httpContextAccessor.HttpContext.Session;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public CartItemsController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            SwimmingClubContext context,
            IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        // GET: CartItems
        public async Task<IActionResult> Index()
        {
            var swimmingClubContext = _context.ShoppingCartItems.Include(c => c.Product);
            var user = await GetCurrentUserAsync();
            var usersShoppingCart = new ShoppingCartActions(_httpContextAccessor, _context);
            //var cartID = usersShoppingCart.GetCartId(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            var cartID = usersShoppingCart.GetCartId(null);


            var cart = await _context.ShoppingCartItems
                .Include(pr => pr.Product)
                .Where(i => i.CartId.Equals(cartID))
                .AsNoTracking()
                .ToListAsync();

            ViewData["CartTotal"] = cart.Sum(c => c.Quantity * c.Product.SellingPrice);
            return View(cart);
        }


        // GET: CartItems/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.ShoppingCartItems.SingleOrDefaultAsync(m => m.ItemId == id);
            if (cartItem == null)
            {
                return NotFound();
            }

            return View(cartItem);
        }

        // GET: CartItems/Create
        public IActionResult Create()
        {
            ViewData["ProductId"] = new SelectList(_context.Products, "ID", "ID");
            return View();
        }

        // POST: CartItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemId,CartId,DateCreated,ProductId,Quantity")] CartItem cartItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cartItem);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "ID", "ID", cartItem.ProductId);
            return View(cartItem);
        }

        // GET: CartItems/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.ShoppingCartItems.SingleOrDefaultAsync(m => m.ItemId == id);
            if (cartItem == null)
            {
                return NotFound();
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "ID", "ID", cartItem.ProductId);
            return View(cartItem);
        }

        // POST: CartItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ItemId,CartId,DateCreated,ProductId,Quantity")] CartItem cartItem)
        {
            if (id != cartItem.ItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cartItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartItemExists(cartItem.ItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "ID", "ID", cartItem.ProductId);
            return View(cartItem);
        }

        // POST: CartItems/Update/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Update(string id,int qty)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.ShoppingCartItems.SingleOrDefaultAsync(m => m.ItemId == id);
            if (cartItem == null)
            {
                return NotFound();
            }

            cartItem.Quantity = qty;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cartItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartItemExists(cartItem.ItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(cartItem);
        }

        // GET: CartItems/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.ShoppingCartItems.SingleOrDefaultAsync(m => m.ItemId == id);
            if (cartItem == null)
            {
                return NotFound();
            }

            return View(cartItem);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var cartItem = await _context.ShoppingCartItems.SingleOrDefaultAsync(m => m.ItemId == id);
            _context.ShoppingCartItems.Remove(cartItem);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool CartItemExists(string id)
        {
            return _context.ShoppingCartItems.Any(e => e.ItemId == id);
        }
        #region Helpers

        private Task<ApplicationUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        #endregion
    }
}

src/WebApplication4/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BWSC.Data;
using BWSC.Models;
using BWSC.Logic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace BWSC.Models
{
    public class ProductsController : Controller
    {
        private readonly SwimmingClubContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private ShoppingCartActions usersShoppingCart;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public ProductsController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            SwimmingClubContext context, 
            IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            _userManager = userManager;
            _signInManager = signInManager;
            usersShoppingCart = new ShoppingCartActions(_httpContextAccessor, _context);
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var cartID = usersShoppingCart.GetCartId(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            //ViewData["CartCount"] = usersShoppingCart.GetCartItems().Count;
            List<Product> products = await _context.Products.ToListAsync();
            List<CartItem> cartItems = await _context.ShoppingCartItems
                .Where(i => i.CartId.Equals(cartID))
                .ToListAsync();

            var ProductsList = from p in products
                        join c in cartItems on p.ID equals c.ProductId into cp
                        from ProductCart in cp.DefaultIfEmpty()
                        select new {p.ID,p.ShortName,p.Description,p.SellingPrice, p.ImageFileName
                        , Quantity = (ProductCart == null ? 0 : ProductCart.Quantity
                        ) };

            ViewData["CartCount"] = ProductsList.Sum(cart => cart.Quantity);

            return View(products);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.SingleOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Description,ImageFileName,SellingPrice,ShortName")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/AddToCart/5
        public async Task<IActionResult> AddToCart(int? id)
        {
            HttpContext.Session.SetString("a", "b");
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.SingleOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }
            usersShoppingCart.AddToCart(product.ID, this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            return RedirectToAction("Index");
        }

        // POST: Products/AddToCart/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToCart(int id, [Bind("ID,Description,ImageFileName,SellingPrice,ShortName")] Product product)
        {
            if (id != product.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.SingleOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.SingleOrDefaultAsync(m => m.ID == id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ID == id);
        }

        private Task<ApplicationUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }
    }
}

src/WebApplication4/Views/Products/Create.cshtml
@model BWSC.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ImageFileName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ImageFileName" class="form-control" />
                <span asp-validation-for="ImageFileName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SellingPrice" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SellingPrice" class="form-control" />
                <span asp-validation-for="SellingPrice" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ShortName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ShortName" class="form-control" />
                <span asp-validation-for="ShortName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/WebApplication4/Views/Products/Delete.cshtml
@model BWSC.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImageFileName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImageFileName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SellingPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SellingPrice)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShortName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShortName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/WebApplication4/Views/Products/Details.cshtml
@model BWSC.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImageFileName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImageFileName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SellingPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SellingPrice)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShortName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShortName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/WebApplication4/Views/Products/Edit.cshtml
@model BWSC.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ImageFileName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ImageFileName" class="form-control" />
                <span asp-validation-for="ImageFileName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SellingPrice" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SellingPrice" class="form-control" />
                <span asp-validation-for="SellingPrice" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ShortName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ShortName" class="form-control" />
                <span asp-validation-for="ShortName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/WebApplication4/Views/Products/Index.cshtml
@model IEnumerable<BWSC.Models.Product>

@{
    ViewData["Title"] = "Available Products";
}

<h2>
    Shop
    <a class="btn btn-default btn-lg" asp-area="" asp-controller="CartItems" asp-action="Index" style="position:absolute;right:50px;">
        <span class="glyphicon glyphicon-shopping-cart"></span> @ViewData["CartCount"]
    </a>
</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th class="hidden-xs">
                @Html.DisplayNameFor(model => model.ImageFileName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SellingPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShortName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td class="hidden-xs">
                <img class="thumbnail" src="images\@Html.DisplayFor(modelItem => item.ImageFileName)" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SellingPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShortName)
            </td>
            <td>
                <a asp-action="AddToCart" asp-route-id="@item.ID">Add To Cart</a>
            </td>
        </tr>

        
}
    </tbody>
</table>

    